basePath: /
definitions:
  dto.ContactRequest:
    properties:
      email:
        type: string
      job_position:
        type: string
      mobile:
        type: string
      name:
        type: string
      phone:
        type: string
      supplier_id:
        type: integer
    type: object
  models.Contact:
    properties:
      email:
        type: string
      id:
        type: integer
      job_position:
        type: string
      mobile:
        type: string
      name:
        type: string
      phone:
        type: string
      supplier_id:
        type: integer
    type: object
  models.Supplier:
    properties:
      address:
        type: string
      contacts:
        items:
          $ref: '#/definitions/models.Contact'
        type: array
      id:
        type: integer
      logo:
        type: string
      nick_name:
        type: string
      status:
        type: string
      supplier_name:
        type: string
    type: object
host: localhost:1323
info:
  contact: {}
  description: API untuk mengelola data suppliers dan contacts
  title: Supplier API
  version: "1.0"
paths:
  /contacts:
    post:
      consumes:
      - application/json
      description: Tambah contact baru untuk supplier tertentu
      parameters:
      - description: Data Contact
        in: body
        name: contact
        required: true
        schema:
          $ref: '#/definitions/dto.ContactRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Contact'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Tambah contact
      tags:
      - Contacts
  /contacts/{id}:
    delete:
      description: Hapus contact berdasarkan ID
      parameters:
      - description: ID contact
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hapus contact
      tags:
      - Contacts
  /contacts/supplier/{supplier_id}:
    get:
      description: Ambil semua contact berdasarkan supplier ID dengan opsi pagination
      parameters:
      - description: Supplier ID
        in: path
        name: supplier_id
        required: true
        type: integer
      - default: 1
        description: Halaman
        in: query
        name: page
        type: integer
      - default: 10
        description: Jumlah data per halaman
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List kontak berdasarkan supplier
      tags:
      - Contacts
  /suppliers:
    get:
      description: Menampilkan semua data supplier beserta kontak
      parameters:
      - default: 1
        description: Halaman
        in: query
        name: page
        type: integer
      - default: 10
        description: Jumlah data per halaman
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ambil semua supplier
      tags:
      - Suppliers
    post:
      consumes:
      - multipart/form-data
      description: Buat supplier baru dan upload logo
      parameters:
      - description: Nama Supplier
        in: formData
        name: supplier_name
        required: true
        type: string
      - description: Nama Panggilan
        in: formData
        name: nick_name
        type: string
      - description: Alamat
        in: formData
        name: address
        type: string
      - description: Status
        in: formData
        name: status
        type: string
      - description: Logo (gambar)
        in: formData
        name: logo
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Supplier'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Buat supplier baru
      tags:
      - Suppliers
schemes:
- http
swagger: "2.0"
